apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: dev

# Image will be updated by GitHub Actions automatically
images:
- name: my-app
  newName: 2871/my-app
  newTag: 39c4a66aea2e8968627bcc7e432f37ade058cb32

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: dev
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
