apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: dev

# Image will be updated by GitHub Actions automatically
images:
- name: my-app
  newName: 2871/my-app
  newTag: dc865f16cb4cad54c448fb82d4229441aff99085

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: dev
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
