apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: dev

# Image will be updated by GitHub Actions automatically
images:
- name: 2871/my-app
  newName: 2871/my-app
  newTag: 11a056e268a7d2a74239c4cdef0bfd751daefcc0
- name: my-app
  newName: 2871/my-app
  newTag: 3b4aa64eb1bceca22debf96b19804c1c4a721273

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: dev
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
