apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: staging

images:
- name: my-app
  newName: 2871/my-app
  newTag: 8ec4255f9d2930f60db02520365a93154eff5f6e

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: staging
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
