apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: staging

images:
- name: my-app
  newName: 2871/my-app
  newTag: 2efb33b5851c7bdab3405ae93d70cb445252efee

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: staging
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
