apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: prod

images:
- name: my-app
  newName: 2871/my-app
  newTag: 0c74a2736ccff6cf26b9a83f1726307f91a7532a

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
