apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: prod

images:
- name: my-app
  newName: 2871/my-app
  newTag: bb0809b129a83f8a095b367fb79361abd9b98836

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
